build:
  maxIssues: 10

style:
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: true

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: true
  SwallowedException:
    active: true