# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug APK"
  lane :build_debug do
    gradle(task: "assemble", build_type: "Debug")
  end

  desc "Build release APK signed with keystore"
  lane :build_release do
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["MYAPP_RELEASE_STORE_FILE"],
        "android.injected.signing.store.password" => ENV["MYAPP_RELEASE_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["MYAPP_RELEASE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["MYAPP_RELEASE_KEY_PASSWORD"],
      }
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
